### ISSUE TITLE
Error with Armarestarts Crontab

### ISSUE THREAD

**Issue by CrushTub3** [82ndab-Bravo17/b3-arma2plugins#1]
Hello,

im running your armarestarts-plugin with the BigBrotherBot (1.9.2) on Debian 8.5.
If i create a restart i get this Error:

> ERROR    'Exception raised while executing crontab <bound method ArmarestartsPlugin.unlock_server of <armarestarts.ArmarestartsPlugin object at 0x7f10e6545750>>: can only join an iterable\n[(\'/home/arma3server/rcon/b3/cron.py\', 364, \'run\', \'c.run()\'), (\'/home/arma3server/rcon/b3/cron.py\', 89, \'run\', \'self.command()\'), (\'/home/arma3server/rcon/b3/extplugins/armarestarts.py\', 254, \'unlock_server\', "self.console.write(self.console.getCommand(\'unlockserver\',))"), (\'/home/arma3server/rcon/b3/parsers/battleye/abstractParser.py\', 741, \'write\', "cmd = \' \'.join(msg).strip()")]'

I dont know how to fix it. Also, if i want to Restart the Bot, i often have to restart it several times because it doesnt connect to the Battleye-Server.

**Comment by 82ndab-Bravo17** [comment]
Please download the latest version of B3 (1.10) from my big-brother-bot repo, there have been many updates and changes since 1.9.2. This will add the unlock command to the parser and stop that error.

Not sure why the parser isn't connecting, hopefully one of the changes will have fixed that.

**Comment by CrushTub3** [comment]
Works!
And if i restart the Bot after the Server it connect to it!

**Comment by CrushTub3** [comment]
Okay. Now the Arma Server wont come back up again ;(
[b3.txt](https://github.com/82ndab-Bravo17/b3-arma2plugins/files/552451/b3.txt)

**Comment by 82ndab-Bravo17** [comment]
You need to set the correct path for your log file backups:

161026 08:00:13 INFO     'STDOUT \'Error creating folder "<type \\\'exceptions.Exception\\\'>" : [Errno 2] No such file or directory: \\'G:\\\\Arma3_Epoch_2302\\\\SC/logs/_20161026-080013/\\'\''

And you need to have the --restart parameter set in your b3 start command, or have some other way to automatically restart it if it shuts down.

The bot is supposed to do a restart 3 minutes after issuing the #shutdown command - that was done to ensure that it would reconnect correctly to the server when it restarted. If it doesn't, then it looks like the --restart parameter is not working correctly. You can just run the bot with a program that will restart it if it crashes or stops running. We use Firedaemon, but that is for windows - I am sure that there is something that will work for Linux. Or i expect that you can write a custom shell program to check that b3 is still running, and start it if it isn't, similar to the .BAT file that can be used in windows.

If you mean that the Amra3 server itself is not restarting, then you need a similar shell program to restart it.

**Comment by CrushTub3** [comment]
The Armaserver needs to be startet manualy after the restartscript should have restarted the Server. I have changed the Logfile Path and also i start with --restart.
The Script is sending the shutdown command and after that nothing happens!
I think the Script also starts the Server...

**Comment by 82ndab-Bravo17** [comment]
You need to have a shell program that checks that the Arma3 server is running, and restarts it if not. That is usually how servers are set up, so that they restart automatically if they crash.

The same for B3 if --restart isn't working.
